### ISSUE TITLE
SSH and Conda tests failing

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/niceman#124]
Using Debian 9.

Commit 4ae06f9 is okay.

Commit 2e53e36 introduces the error in [error1.txt](https://github.com/ReproNim/niceman/files/1395800/error1.txt).

Commit d4bdac7 introduces the error in [error2.txt](https://github.com/ReproNim/niceman/files/1395802/error2.txt).

**Comment by chaselgrove** [comment]
@mjtravers can we set up a fixture for test_ssh_class() in niceman/resource/tests/test_ssh.py?  It appears that this test requires docker, which currently is only set up in travis, so `niceman test` fails.

**Comment by chaselgrove** [comment]
Error 2 went away after clearing my niceman cache (rm -r ~/.cache/niceman).

**Comment by rbuccigrossi** [comment]
Right. If something goes wrong in setting up miniconda in ~/.cache/niceman (or it is interrupted), then detection will fail. By clearing out ~/.cache/nicema/conda_test, it reconstructed the conda environment and appeared to pass the second time around.

**Comment by mjtravers** [comment]
Yeah, we need a decorator like "skip_if_no_docker" for the test functions. I will see if I can put one together.

**Comment by chaselgrove** [comment]
@mjtravers, I just saw your comment -- I hope you weren't working on this since then!
