### ISSUE TITLE
performance: probably need to bundle all apt-cache policy and show calls

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#142]
ATM retracing invokes those per each package separately.  But it seems that there is a major startup penalty in those commands (when considering multiple invocations).  I guess the only way is to do two pass analysis -- collect the list of all packages to be considered, pass to those commands in a single invocation for each, and then analyze for per package information.  Should provide a notable speed up ;-)

**Comment by rbuccigrossi** [comment]
From today's discussion:

  The best general approach is to update DebTracer::identify_distributions() to not call the base class identify_package_from_files(), but instead loop through the files and gather all the package names first (This is what CondaTracer does now). That way we can get the details of all the packages in one shot.

  We use a number of system calls (dpkg -s, apt-cache show, and apt-cache policy) that support multiple packages nicely. We also use "stat" on the <pkg>.list file to get the creation date (representing the install date of the package).  To get stat to display the date and the filename, we should switch the current call to something like:

```shell
stat -c "%n: %Y" filename1 filename2
```

This will allow us to parse both the filename and the create date timestamp for each file.
