### ISSUE TITLE
retrace output spec shouldn't include all the fields with no value (null)

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#164]
e.g. as shown in https://github.com/ReproNim/niceman/issues/160

**Comment by kyleam** [comment]
Duplicate of #105? (or perhaps a more general issue that includes #105
if it happens for fields other than `pushurl`)

**Comment by yarikoptic** [comment]
d'oh -- right, I've forgotten already that I've complained already and even assigned to myself. heh - will fix now so it doesn't come back for the 3rd time ;)  not sure yet if generic, so I will fix only for pushurl
