### ISSUE TITLE
Runner()([], shell=True) runs only the first command in the list of commands

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#169]
originally discovered while trying to provide an example in review of https://github.com/ReproNim/niceman/pull/162

```ipython
In [14]: lgr.setLevel(1)

In [15]: Runner()(["ls", ".", ";", "echo", "123"], shell=True)
2018-02-01 11:44:27,608 [DEBUG  ] Running: ['ls', '.', ';', 'echo', '123'] 
2018-02-01 11:44:27,613 [DEBUG  ] stdout| CHANGELOG.md
| CONTRIBUTING.md
...
| venvs 
2018-02-01 11:44:27,613 [Level 8] Finished running ['ls', '.', ';', 'echo', '123'] with status 0 
Out[15]: 
('CHANGELOG.md\nCONTRIBUTING.md\nCOPYING\ndist\ndocker-compose.yml\nDockerfile\ndocs\nformatters.py\nformatters.pyc\nniceman\nniceman.cfg\nniceman.egg-info\nREADME.md\nreadthedocs.yml\nrequirements-devel.txt\nrequirements.txt\nsetup.cfg\nsetup.py\nsetup_support.py\nsetup_support.pyc\nSingularity\ntools\ntox.ini\nvenvs\n',
 '')
```

@kyleam , could you have a look please?

**Comment by kyleam** [comment]
> @kyleam , could you have a look please?

absolutely

**Comment by kyleam** [comment]
If you boil it down to

```
import subprocess
subprocess.Popen(["ls", ".", ";", "echo", "123"], shell=True)
```

you see the same.  The output only consists of the output from `ls .`.
I think the core issue is that `shell=True` is only intended to be
used with a string command, though I can't find that explicitly
documented.  I can only find the [reverse said][0]:

> If passing a single string, either shell must be True (see below) or
> else the string must simply name the program to be executed without
> specifying any arguments.

[0]: https://docs.python.org/2/library/subprocess.html#frequently-used-arguments
