### ISSUE TITLE
conda tracer expects 'ENV/bin/conda' to always be present

### ISSUE THREAD

**Issue by kyleam** [ReproNim/niceman#173]
This assumption makes conda retracing fail (in at least some cases)
under miniconda3.

As an example, start from a fresh environment and install `attrs`.

```
$ ~/miniconda2/bin/conda --version
conda 4.3.31
$ ~/miniconda3/bin/conda --version
conda 4.4.8

$ ~/miniconda2/bin/conda info --envs
# conda environments:
#
root                  *  ~/miniconda2
$ ~/miniconda3/bin/conda info --envs
# conda environments:
#
base                  *  ~/miniconda3

$ ~/miniconda2/bin/conda install --yes -m -n nmtest attrs
$ ~/miniconda3/bin/conda install --yes -m -n nmtest attrs
```

If I retrace a file from miniconda2's `attrs`, I see it assigned to
the `attrs` package as expected:

```
$ niceman retrace ~/miniconda2/envs/nmtest/lib/python2.7/site-packages/attr/validators.py
[...]
distributions:
- name: conda
  path: ~/miniconda2
  conda_version: 4.3.31
  python_version: 2.7.14.final.0
  environments:
  - name: conda_env
    path: ~/miniconda2/envs/nmtest
    conda_version: 4.3.31
    python_version: 2.7.14.final.0
    packages:
    [...]
    - name: attrs
      version: 17.4.0
      build: py27_0
      channel_name: defaults
      size: 41432
      md5: 307732cf9ad2fc0783c5af9d5a16cf6f
      url: https://repo.continuum.io/pkgs/main/linux-64/attrs-17.4.0-py27_0.tar.bz2
      files:
      - lib/python2.7/site-packages/attr/validators.py
```

If I do the same under miniconda3, this file isn't assigned.

```
$ niceman retrace ~/miniconda3/envs/nmtest/lib/python3.6/site-packages/attr/validators.py
[...]
distributions:
- name: conda
  path: ~/miniconda3
  conda_version: 4.4.8
  python_version: 3.6.3.final.0
  environments:
  - name: conda_env
    path: ~/miniconda3
    conda_version: 4.4.8
    python_version: 3.6.3.final.0
    packages:
      [... no attrs package here]
files:
- ~/miniconda3/envs/nmtest/lib/python3.6/site-packages/attr/validators.py
```

I believe this is because the `_get_conda_info` method expects the
environment to always have `conda` in its bin directory:

https://github.com/ReproNim/niceman/blob/30ae824fe3696a3a92ee34e28bf65a772cff8b15/niceman/distributions/conda.py#L258-L269

But this isn't the case for miniconda3:

```
$ ls -1 ~/miniconda2/envs/nmtest/bin/ | grep conda
conda
$ ls -1 ~/miniconda3/envs/nmtest/bin/ | grep conda
```

If I install conda into the miniconda3 environment, retracing works:

```
$ ~/miniconda3/bin/conda install --yes -m -n nmtest conda
$ niceman retrace ~/miniconda3/envs/nmtest/lib/python3.6/site-packages/attr/validators.py
[...]
distributions:
- name: conda
  path: ~/miniconda3/envs/nmtest
  conda_version: 4.4.8
  python_version: 3.6.4.final.0
  environments:
  - name: conda_env
    path: ~/miniconda3/envs/nmtest
    conda_version: 4.4.8
    python_version: 3.6.4.final.0
    packages:
    [...]
    - name: attrs
      version: 17.4.0
      build: py36_0
      size: 42175
      md5: c75b22962b744a71306b6a4c5d6c81a7
      url: https://repo.continuum.io/pkgs/main/linux-64/attrs-17.4.0-py36_0.tar.bz2
      files:
      - lib/python3.6/site-packages/attr/validators.py
```

**Comment by rbuccigrossi** [comment]
That's very interesting...  I quickly updated the test_conda.get_conda_test_dir() function to use Miniconda3-latest instead of Miniconda2-latest, blew away my .cache/niceman directory, and full expected the test to fail (as a first step to fixing it).  However, it passed!  Sure enough, there was an envs/mytest/bin/conda file sitting there.  However, I realize that created the environment with "conda create y -n mytest python=2.7"

In your set of commands, it looks like you install attrs into a new environment without "create".  Is that normal?

**Comment by kyleam** [comment]
Thanks for trying to reproduce this on your end.

> However, it passed! Sure enough, there was an envs/mytest/bin/conda file sitting there.

Now I'm happy I tacked "in at least some cases" onto my opening line :)

> In your set of commands, it looks like you installed attrs into a new environment without first calling "create" on that environment. Is that normal?

Good question.  I have no idea how common it is, but I suppose `conda`
does support it (rather than it working by chance) in the sense that
it's why the `-m/--mkdir` flag exists, I think.

I'll try to modify my test scripts to create the environment in a
separate step and see what happens.

Though I suppose in both the miniconda2 vs 3 invocations I did it
without calling `create`, so I still find the difference puzzling.

**Comment by kyleam** [comment]
> I'll try to modify my test scripts to create the environment in a
> separate step and see what happens.

I'm still seeing the issue if I create the environment before and if I
use `python=2.7` for the miniconda3 call.

Here is the script in case it helps, though the paths are of course
specific for my machine.


```bash
#!/bin/bash
set -x

~/miniconda2/bin/conda --version
~/miniconda3/bin/conda --version

~/miniconda2/bin/conda info --envs
~/miniconda3/bin/conda info --envs

~/miniconda2/bin/conda create --yes -n nmtest
~/miniconda2/bin/conda install --yes -n nmtest attrs

~/miniconda3/bin/conda create --yes -n nmtest python=2.7
~/miniconda3/bin/conda install --yes -n nmtest attrs

source ~/src/python/niceman/venv3/bin/activate
niceman retrace ~/miniconda2/envs/nmtest/lib/python2.7/site-packages/attr/validators.py
niceman retrace ~/miniconda3/envs/nmtest/lib/python2.7/site-packages/attr/validators.py

ls -1 ~/miniconda2/envs/nmtest/bin/ | grep conda
ls -1 ~/miniconda3/envs/nmtest/bin/ | grep conda

~/miniconda3/bin/conda install --yes -m -n nmtest conda

niceman retrace ~/miniconda3/envs/nmtest/lib/python2.7/site-packages/attr/validators.py
```

**Comment by kyleam** [comment]
And like you I can get the tests to fail.

I wiped the cache and tried with

```diff
diff --git a/niceman/distributions/tests/test_conda.py b/niceman/distributions/tests/test_conda.py
index 8aa0ca9..21365a7 100644
--- a/niceman/distributions/tests/test_conda.py
+++ b/niceman/distributions/tests/test_conda.py
@@ -37,9 +37,9 @@ def get_conda_test_dir():
         return test_dir
     # Miniconda isn't installed, so install it
     if sys.platform.startswith('darwin'):
-        miniconda_sh = "Miniconda2-latest-MacOSX-x86_64.sh"
+        miniconda_sh = "Miniconda3-latest-MacOSX-x86_64.sh"
     elif sys.platform.startswith('linux'):
-        miniconda_sh = "Miniconda2-latest-Linux-x86_64.sh"
+        miniconda_sh = "Miniconda3-latest-Linux-x86_64.sh"
     else:
         raise ValueError("Conda test not supported with platform %s " %
                          sys.platform)
```

**Comment by kyleam** [comment]
Right, so I somehow I must have put my ~/miniconda3/ into a confused
state.  It consistently does **not** add 'bin/conda' when I create a
new environment.  However, if I use the same miniconda3 install script
to install miniconda3 under a new prefix, it does create the
'bin/conda'.  Dunno.  Anyway, closing.  Sorry for the noise.
