### ISSUE TITLE
Latest conda release breaks conda directory detection

### ISSUE THREAD

**Issue by rbuccigrossi** [ReproNim/niceman#187]
In the latest conda release, it appears that new environments don't get bin/conda by default anymore.  This breaks our conda directory detection and our call to get conda information. I'll address this as part of #174.

**Comment by kyleam** [comment]
Hmm I wonder if this was the underlying cause of my issues in #173

**Comment by rbuccigrossi** [comment]
Ugh.  This breaks a lot of the technique that we use for detection.

Right now we grab the various paths, and then use ENV/bin/conda to get the common root_prefix.  Without bin/conda we can't find the root directly from the child.  (More fun: they now call "root" the "base".)

**Comment by yarikoptic** [comment]
what is the conda release which changed the behavior?

**Comment by rbuccigrossi** [comment]
4.4.0 changed the behavior.  (I used "update" to change various versions of conda, which is nice since you can downgrade from 4.4.10 to any 4.4.x and even 4.3.31.)

It looks like they switched "latest" from 4.3.31 to 4.4.10.

Because there isn't a "bin" directory, now you activate the environment by running

source activate env_name

where activate is in the root's bin directory.

**Comment by kyleam** [comment]
Fixed by #186.
