### ISSUE TITLE
Git VCS add a hexsha of the root commit

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#228]
Add another field for the record to point to the "root-hexsha"
```shell
$> git rev-list --reverse --left-only master | head -n 1
```
which would help to identify repositories (unless they started from the template repo like shablona)

**Comment by chaselgrove** [comment]
Do we need --left-only when we're after the first commit?

**Comment by kyleam** [comment]
> Do we need --left-only when we're after the first commit?

No, as [mentioned in the pr][0], --left-only is only relevant when you're working symmetric differences

[0]: https://github.com/ReproNim/niceman/pull/232#discussion_r190720832

**Comment by kyleam** [comment]
Closed by #232.
