### ISSUE TITLE
Recent docker test failures

### ISSUE THREAD

**Issue by kyleam** [ReproNim/niceman#254]
Seems like the hardcoded alpine ID is stale:

```
______________________________ test_docker_trace _______________________________
    @skip_if_no_network
    @skip_if_no_docker_engine
    def test_docker_trace():
        client = docker.Client()
        client.pull('alpine:3.6')

        tracer = DockerTracer()

        files = ['alpine:3.6', 'non-existant-image']
        dist, remaining_files = next(tracer.identify_distributions(files))
        assert dist.name == 'docker'
>       assert dist.images[0].id == 'sha256:77144d8c6bdce9b97b6d5a900f1ab85da' + \
            '325fe8a0d1b0ba0bbff2609befa2dda'
E       AssertionError: assert 'sha256:da579...3637cce406126' == 'sha256:77144d...f2609befa2dda'
E         - sha256:da579b235e92c861790f69d621d4601f54892bef262fa3fc38e3637cce406126
E         + sha256:77144d8c6bdce9b97b6d5a900f1ab85da325fe8a0d1b0ba0bbff2609befa2dda
niceman/distributions/tests/test_docker.py:32: AssertionError
```

([source](https://travis-ci.org/ReproNim/niceman/jobs/400948220))

**Comment by kyleam** [comment]
In #203, @mjtravers says

> The hash for the repository hub id (the repo digest) is changing although the local image id seems to be static... at least so far.

It looks like that's no longer the case.

**Comment by yarikoptic** [comment]
so is it just that that particular image tag was removed/replaced and previous one was "garbaged out"?
I think we need to generate/use our own to avoid such troubles

**Comment by kyleam** [comment]
> so is it just that that particular image tag was removed/replaced and previous one was "garbaged out"?

The tag must have been updated.  The previous image is still available though:

```bash
%> docker pull alpine@sha256:f625bd3ff910ad2c68a405ccc5e294d2714fc8cfe7b5d80a8331c72ad5cc7630

%> docker inspect 77144d8c6bdc | jq '.[0].RepoDigests'
[
  "alpine@sha256:f625bd3ff910ad2c68a405ccc5e294d2714fc8cfe7b5d80a8331c72ad5cc7630"
]
```

> I think we need to generate/use our own to avoid such troubles

Yeah, I know that's come up before.  I think it's a good idea.
