### ISSUE TITLE
OSX: we should not deman installation of reprozip

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#276]
it is not available for anything but linux and thus now `pip install niceman` fails on osx

**Comment by remram44** [comment]
You can use something like:
```python
install_requires=[
    'reprozip; sys_platform=="linux" or sys_platform=="linux2"'
]
```
See [PEP 508](https://www.python.org/dev/peps/pep-0508/)

**Comment by kyleam** [comment]
@remram44 Thanks!
