### ISSUE TITLE
basic test (to be ran on Travis) for `start/stop`

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#282]
As coverage in https://github.com/ReproNim/niceman/pull/274/files#diff-25ab1a3d97e48f83f77bd87b4a748fb1R44 suggests, there is no test which is ran on travis for at least basic coverage

**Comment by yarikoptic** [comment]
sideeffect:
```
$> niceman stop test-ec2-west
2018-09-06 14:29:24,440 [ERROR  ] 'NoneType' object has no attribute 'stop' [aws_ec2.py:stop:201] (AttributeError) 
```

**Comment by kyleam** [comment]
With the merge of #287, that leaves figuring out why `_ec2_instance` is None here:

https://github.com/ReproNim/niceman/blob/2de5e44ed11ff65df6f037217d911add19cd2b76/niceman/resource/aws_ec2.py#L197-L201

**Comment by yarikoptic** [comment]
because it seems only the `create` is the one assigning it?  should be lazily instantiated I guess if not defined based on the config

**Comment by yarikoptic** [comment]
EC2 issue got a dedicated https://github.com/ReproNim/niceman/issues/317 now
