### ISSUE TITLE
Why does login have a --backend option?

### ISSUE THREAD

**Issue by kyleam** [ReproNim/niceman#290]
It looks like I unintentionally made login's `--backend` a noop in 309bdbbe (RF: Absorb more resource handling into ResourceManager, 2018-07-27). I was going to try to add it back, but then I realized that I don't understand login's support for `--backend`. Scanning through the options the `backend_help` lists, I don't see any that seem like they would be relevant at **log in**, only creation.

Am I missing something? Should `login` have a `--backend` option?

**Comment by yarikoptic** [comment]
Unless we make it also "create" indeed there should be no reason ;)

**Comment by kyleam** [comment]
OK, thanks for the second set of eyes.
