### ISSUE TITLE
ENH: specify backend parameters as a dict from within Python

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#312]
A chaser to #303:  ATM within Python API we need to provide cmdline like list of "param=value"s, which we then convert to a dict.  So I wondered if we should also allow for it to be a dict to start with, so in addition to
```python
nm.create("test", "docker-container", ["image=debian:testing"])
```
```python
nm.create("test2", "docker-container", {'image': 'debian:testing'})
```
would work?

**Comment by kyleam** [comment]
Sounds like a good idea to me.

**Comment by yarikoptic** [comment]
cool, should be just a matter of checking if not a dict already in `parse_backend_parameters`?

**Comment by kyleam** [comment]
> cool, should be just a matter of checking if not a dict already in parse_backend_parameters?

yep
