### ISSUE TITLE
`run` WiP review notes

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#314]
Since there is no PR (yet), I've decided to collect some notes here on reviewing @kyleam 's WiP https://github.com/ReproNim/niceman/compare/master...kyleam:scratch/nf-run

# job spec

## resource_name

seems to require `resource_name` as the leading level, but why?  shouldn't job spec should be about job, and not about resource?  we would specify the resource as the argument to `run`, so the job could be submitted to different resources without modifying job spec itself.  But see below a related item in "ability to tune from cmdline/call?"

## PBS-agnostic job requirements?

relates to above and may be was envisioned already to be done that way later.  IMHO we should aim to avoid PBS specific parameters in the job spec (i.e.`pbs_l_args`) and define a list of the ones we would map into corresponding PBS arguments (have `requirements` with `.walltime`, `.runtime`, `.memory`) .  How does gc3pie specifies those?  E.g. [gc3pie](https://gc3pie.readthedocs.io/en/master/programmers/api/gc3libs.html?highlight=requested_walltime) provides those for jobs specification (`requested_walltime`, etc)

### ability to tune from cmdline/call?

Generally: ideally any "job spec" related change could be done in command line.  With that in mind, `command` itself could be defined in `job.yaml`, so below examples are as if we did not consider it as something special in the cmdline API for now.  So prototypical invocations could be

   - `niceman run -r discovery --js common4allmyjobs.yaml -j command "myscript.py -param1"`
      where I added `-j` to be able to override/add any job spec argument.  Levels within yaml dict structure would be separated by `.`.  I do  not yet foresee any need to reference arrays/lists (I could be wrong). 
So in this command I am pretty much mimicing what is done now, just adding `-j command` to explicitly point that it is the field within jobspec to be modified
   - `niceman run -r discovery  --js myanalysis.yaml -j requirements.memory 1gb -j requirements.walltime 120h -j comment "This is a real thing which needs a lot of time / memory" --input fullsizeddataset`
      where `myanalysis.yaml` is the analysis "specification" which already has a `command` listed (with the `{inputs}` placeholder in the command) and even possibly has already some requirements specified, but they might not be appropriate for the "fullsizeddataset", which is what I am overriding from the command line.
   - above commands should be "executable" with `-r hydra` which would be another resource which uses another batch system (condor)
   - then going further, may be "resource" should be a part of the job spec, but otherwise a subject for the aforementioned overrides in the same way?  This way we might be able to support specification of "execute on multiple resources" (where specification would be a list of items, `-j resource hydra discovery`) after we figure out also how to introduce parametrization of the job (run the same command template with different substitutions, e.g. sweeping through subjects).
   - `datalad run` (or like) commit record:  Probably a "full" (after considering all cmdline arguments) job record should be established/recorded in some niceman sentinel file (e.g. `.niceman/jobs/jobid/jobspec.yaml`).  Or may be it would be a regalar `datalad run` record but with some information (additional field) about the resource/requirements which was used to execute it?

**Comment by kyleam** [comment]
Looking over this, I think most of this is already addressed by #331 (either by what's already there or the to-do comments).  I'll add one bit over there, but please feel free to add anything else I overlooked.
