### ISSUE TITLE
Reduce verbosity of tests on Travis

### ISSUE THREAD

**Issue by kyleam** [ReproNim/niceman#322]
We're dumping too much to stdout/stderr in our tests.  Travis's online interface currently reports

    This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.

which makes debugging failures less convenient.

Quickly glancing at [a log], some of the main offenders are

  * test_debian (biggest offender, it seems)
  * pip install
  * formats/tests/test_niceman
  * tests_retrace
  * test_docker_container.py

[a log]: https://api.travis-ci.org/v3/job/447955542/log.txt

**Comment by yarikoptic** [comment]
alternative could be just to strip away `-v` from py.test run options?

**Comment by kyleam** [comment]
> alternative could be just to strip away -v from py.test run options?

We already run without `-v`:

https://github.com/ReproNim/niceman/blob/cd17165699eb1bc2cfbc44865eba81afd65f6c32/.travis.yml#L79

Also, that output is a tiny blip compared to what test_debian is currently dumping out.

**Comment by yarikoptic** [comment]
Sorry, I meant -s

**Comment by kyleam** [comment]
> Sorry, I meant -s

It was enabled due to some interaction with fabric (gh-296), though the commit message in 3ef0f5c0 (Added -s switch for pytest in travis, 2018-09-13) doesn't shed much light on it.  @mjtravers, can you recall the details?

**Comment by kyleam** [comment]
> @kyleam Introducing fabric caused pytest to fail due to stderr/stdout contention issues. Here's the link referenced in the PR comment about the problem ([gh-296](https://github.com/ReproNim/niceman/pull/296)): http://lists.idyll.org/pipermail/testing-in-python/2011-December/004616.html

Thanks.  Sorry for overlooking that link.

> In general may be take as a practice to not have any `print` statements within tests... we have only a handful atm:

Yep, I was planning to have a look at this later today.
