### ISSUE TITLE
rename...

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/niceman#44]
please change name back to NICEMAN

**Comment by yarikoptic** [comment]
What will be the repronim?

**Comment by dnkennedy** [comment]
the collection of tools, including NeuroBlast, BrainVerse and NICEMAN is the collection of tools that is Repronim...

**Comment by yarikoptic** [comment]
ok - we will rename on Thur

**Comment by yarikoptic** [comment]
was renamed awhile back, RiP unified kingdom of repronim, welcome a union of repronim suits ;-)
