### ISSUE TITLE
Identify debian and neurodebian snapshots URL date from Release file date

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#66]
See the thread on debian-snapshots where details were somewhat flashed out: https://lists.debian.org/debian-snapshot/2016/08/msg00004.html

**Comment by mjtravers** [comment]
We are not looking at the Release file but, for now, scraping the snapshot page for the next snapshot date in the "next" link.

This was coded up in PR #140 

Closing issue
