### ISSUE TITLE
test demands interaction

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#70]
in enh_close (with some of my changes but those shouldn't be relevant):
```
niceman/tests/test_cmdline_main.py::test_usage_on_insufficient_args Enter a resource name: 
```

**Comment by mjtravers** [comment]
Yes, I have a fix for this. I will push it. I've been holding on to it while I try and figure out why my inventory mock is not getting picked up in ubuntu.

**Comment by mjtravers** [comment]
This has been fixed.
