### ISSUE TITLE
compare (re)tracing between reprozip and regular strace 

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#90]
so we want to see  (on the example of simple workflow)
- how much of overhead in comparison to regular not traced execution
- either strace provides as complete coverage in terms of files as reprozip, or what would be the differences?
- what additional features of ptrace within reprozip in comparison to strace (which with some additional options AFAIK could provide info about all the arguments to syscalls etc).  you could also look into testkraut for a sample of switches to give to strace
- coordinate with @rbuccigrossi so this is accomplished on the shared account/box where we could both retrace.   We might actually just create a dedicated singularity or docker image for that purpose so to reuse it locally

**Comment by rbuccigrossi** [comment]
Some observations:

- Reprozip records one run per trace (it can combine multiple traces). (pytracer.c line 117 calls "fork_and_trace" once, which in turn on line 742 of tracer.c, which calls "db_add_first_process" once). 
  - The SQLLite schema can support multiple runs
- You can collect multiple runs by "continuing" (-c) on a new reprozip trace call.
- Reprozip records file open, exec, connection (network), and exit events into SQLLite, but only uses the first process and file open events in the configuration
- Strace by itself sill not be enough to capture all of the file data (specifically the shebang executable and related linked libraries).  Reprozip gathers this information from /proc/$PID/maps

**Comment by satra** [comment]
hey folks just an fyi to the neurodocker addition for reprozip:

https://github.com/freesurfer/freesurfer/issues/70#issuecomment-316361886

**Comment by yarikoptic** [comment]
thanks @rbuccigrossi , your summary suffices for now, so closing
