### ISSUE TITLE
RF ResourceManager to contain inventory

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/niceman#96]
ATM ResourceManager is just a class with staticmethods which loads and returns config and inventory from the files.  It should provide an instance which encapsulates access and management of the resources.  So that instead of working in code with those returned inventory dictionaries we could request a resource matching e.g. name and/or id, i.e. have a method `get_resource(self, name=None, id=None)` either returning None if nothing matched, or raising some ResourceNotFound exception

**Comment by kyleam** [comment]
`ResourceManager.get_resource` provides this as of 309bdbbe (RF: Absorb more resource handling into ResourceManager, 2018-07-27).
